[project]
name = "def-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.119.0",
    "python-jose[cryptography]>=3.5.0",
]
